language: java
jdk:
  - oraclejdk8
env:
  matrix:
    - PROFILE=ci
    - PROFILE=spring32-next
    - PROFILE=spring4
    - PROFILE=spring4-next
    - PROFILE=spring41
    - PROFILE=spring41-next
    - PROFILE=spring42-next
    - PROFILE=querydsl-next
sudo: false
cache:
  directories:
    - $HOME/.m2
install: true
script: "mvn clean dependency:list test -P${PROFILE} -Dsort"