language: java

jdk:
  - oraclejdk8

env:
  matrix:
    - PROFILE=ci
    - PROFILE=spring43-next
    - PROFILE=spring5
    - PROFILE=spring5-next
    - PROFILE=spring51
    - PROFILE=spring51-next
    - PROFILE=spring52
    - PROFILE=spring52-next
    - PROFILE=querydsl-next

cache:
  directories:
    - $HOME/.m2

install: true

script: "mvn clean dependency:list test -P${PROFILE} -Dsort -U"

notifications:
  slack:
    secure: PWyr3+7uTnHzZSrJY2DrowwdYODlIeFZB6tzuq+i/vYqMlX2GGXGQN9YmqbKPeaVZBdSI7YrI1UDa5cPAAXoTjn/JewkL0RbdTeIS6PGCpcpAb5rFMYtOhEDBrFB/SRiMH4tw86bRNKq/SrUWmpkzDtTzLrw7JceumgyqnrT6GY=
